/**
 * 유명 아티스트 스타일 DB — smart-fallback용
 * LLM 없이도 아티스트명만으로 정밀한 음악 분석 결과를 반환
 *
 * 각 항목: names(매칭 키워드), genre, mood, energy, bpm, key,
 *          instruments, vocalStyle, vocalGender, structure, ref,
 *          moodTags, lyricsTheme, lyricsStyle
 */

module.exports = [
  // ════════════════════════════════════════
  // ── 2000s K-R&B / 소울 발라드 ──
  // ════════════════════════════════════════
  { names: ['brown eyes', '브라운아이즈'], genre: '2000s K-R&B Ballad', mood: 'melancholic', energy: 'low', bpm: 72, key: 'Dm', instruments: 'grand piano arpeggios, lush orchestral strings, finger bass, soft brushed drums, warm reverb pad', vocalStyle: 'male duo harmony vocal with smooth falsetto and emotional vibrato', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus-outro', ref: 'early 2000s Korean R&B ballad with piano arpeggios and lush string arrangements, warm analog production', moodTags: 'melancholic, sentimental, yearning, heartfelt, bittersweet, warm, lush, romantic, tender, nostalgic, analog, smooth', lyricsTheme: '이별의 아픔과 그리움, 시간이 흘러도 잊지 못하는 사랑', lyricsStyle: '서정적 감성 표현, 은유적 이별 묘사' },
  { names: ['brown eyed soul', '브라운아이드소울'], genre: '2000s K-Soul / R&B', mood: 'warm', energy: 'medium', bpm: 85, key: 'Eb', instruments: 'rhodes piano, warm bass guitar, crisp snare, hi-hat groove, string section, brass stabs', vocalStyle: 'male group harmony with soulful ad-libs and rich falsetto', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'Korean neo-soul with Motown influence, warm analog mix, rich vocal harmonies', moodTags: 'soulful, warm, groovy, smooth, sophisticated, rich, jazzy, heartfelt, uplifting, retro, polished', lyricsTheme: '사랑의 따뜻함과 감사, 깊은 감성', lyricsStyle: '소울풀한 감성 표현' },
  { names: ['sg워너비', 'sg wanna be', 'sg wannabe'], genre: 'K-Power Ballad', mood: 'emotional', energy: 'medium', bpm: 70, key: 'Cm', instruments: 'grand piano, sweeping orchestral strings, cello solo, acoustic guitar, soft kick and snare', vocalStyle: 'powerful male trio vocal with soaring high notes and emotional belting', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'epic Korean power ballad with cinematic string arrangements and powerful vocal climax', moodTags: 'emotional, powerful, soaring, dramatic, heartfelt, cinematic, epic, passionate, yearning, lush', lyricsTheme: '깊은 사랑과 이별의 감정, 절절한 그리움', lyricsStyle: '감성적이고 직설적인 사랑 표현' },
  { names: ['바이브', 'vibe'], genre: 'K-R&B Ballad', mood: 'melancholic', energy: 'low', bpm: 68, key: 'Am', instruments: 'acoustic piano, soft strings, gentle bass, brushed drums, warm pad', vocalStyle: 'tender male vocal with delicate vibrato and emotional falsetto', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'tender Korean R&B ballad with intimate piano and soft string bed', moodTags: 'melancholic, tender, intimate, heartfelt, gentle, warm, emotional, bittersweet, yearning, soft', lyricsTheme: '사랑하는 사람에 대한 그리움과 애절함', lyricsStyle: '섬세한 감성 묘사' },
  { names: ['4men', '포맨'], genre: 'K-Power Ballad', mood: 'emotional', energy: 'medium', bpm: 72, key: 'Bbm', instruments: 'piano, orchestral strings, electric guitar arpeggios, bass, drums with fills', vocalStyle: 'powerful male vocal with explosive high register and emotional dynamics', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'dramatic Korean power ballad with explosive vocal climax and orchestral swells', moodTags: 'emotional, dramatic, powerful, passionate, soaring, intense, heartfelt, epic, yearning, expressive', lyricsTheme: '이별 후 후회와 절절한 사랑 고백', lyricsStyle: '직설적인 감정 표현, 드라마틱한 전개' },
  { names: ['먼데이키즈', 'monday kiz'], genre: 'K-Emotional Ballad', mood: 'melancholic', energy: 'low', bpm: 66, key: 'Gm', instruments: 'piano, acoustic guitar, soft strings, gentle percussion, warm bass', vocalStyle: 'emotional male vocal with breathy tone and tender high notes', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'intimate Korean emotional ballad with acoustic warmth and gentle arrangement', moodTags: 'melancholic, intimate, tender, yearning, gentle, bittersweet, emotional, warm, sincere, poignant', lyricsTheme: '이별의 아픔과 후회, 잊지 못하는 기억', lyricsStyle: '일상적 언어로 풀어낸 이별 감성' },
  { names: ['플라이투더스카이', 'fly to the sky'], genre: '2000s K-R&B Ballad', mood: 'emotional', energy: 'medium', bpm: 75, key: 'Fm', instruments: 'piano, R&B bass, strings, soft drums, synth pad, acoustic guitar', vocalStyle: 'male duo vocal with powerful high notes and smooth R&B delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'polished 2000s Korean R&B ballad with powerful duo vocal harmonies and lush arrangement', moodTags: 'emotional, powerful, smooth, romantic, soaring, heartfelt, polished, R&B, passionate, warm', lyricsTheme: '사랑과 이별의 절절한 감정', lyricsStyle: '감성적인 R&B 스타일 가사' },
  { names: ['god', '지오디'], genre: '2000s K-Pop Ballad', mood: 'emotional', energy: 'medium', bpm: 80, key: 'C', instruments: 'piano, acoustic guitar, strings, bass, drums, light synth', vocalStyle: 'male group vocal with emotional harmonies and powerful lead vocal', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'early 2000s Korean pop ballad with heartfelt group vocals and warm arrangement', moodTags: 'emotional, warm, nostalgic, heartfelt, friendly, sincere, comforting, touching, sentimental, bright', lyricsTheme: '우정, 사랑, 추억의 소중함', lyricsStyle: '진솔하고 따뜻한 감정 표현' },
  { names: ['김건모'], genre: '90s K-Pop / Dance Ballad', mood: 'energetic', energy: 'high', bpm: 118, key: 'Am', instruments: 'synth bass, electronic drums, brass, piano, funk guitar, strings', vocalStyle: 'charismatic male vocal with wide range and dynamic pop delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: '90s Korean pop with dance elements, brass hooks and charismatic vocal, retro production', moodTags: 'energetic, retro, groovy, charismatic, bright, danceable, fun, dynamic, catchy, nostalgic', lyricsTheme: '사랑, 이별, 도시적 감성', lyricsStyle: '리드미컬하고 감성적인 표현' },
  { names: ['신승훈'], genre: 'K-Classic Ballad', mood: 'melancholic', energy: 'low', bpm: 65, key: 'Db', instruments: 'grand piano, orchestral strings, acoustic guitar, soft percussion, cello', vocalStyle: 'classic male ballad vocal with pure tone and emotional restraint', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-final_chorus-outro', ref: 'classic Korean ballad with grand piano and orchestral strings, timeless production', moodTags: 'melancholic, classic, timeless, emotional, pure, elegant, tender, yearning, romantic, refined', lyricsTheme: '영원한 사랑, 이별의 아름다움', lyricsStyle: '문학적이고 시적인 표현' },
  { names: ['이문세'], genre: 'K-Classic Pop Ballad', mood: 'nostalgic', energy: 'low', bpm: 72, key: 'G', instruments: 'acoustic guitar, piano, soft strings, flute, gentle percussion', vocalStyle: 'warm mature male vocal with gentle vibrato and storytelling delivery', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'timeless Korean pop ballad with warm acoustic guitar and mature vocal charm, 80s-90s aesthetic', moodTags: 'nostalgic, warm, timeless, gentle, romantic, classic, tender, serene, comforting, elegant', lyricsTheme: '사랑, 계절, 추억의 아름다움', lyricsStyle: '시적이고 아름다운 가사' },
  { names: ['조성모'], genre: 'K-Pop Ballad', mood: 'emotional', energy: 'medium', bpm: 78, key: 'Eb', instruments: 'piano, strings, acoustic guitar, bass, drums, synth pad', vocalStyle: 'clear powerful male vocal with soaring high notes and emotional vibrato', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'late 90s Korean pop ballad with clear powerful vocal and orchestral arrangement', moodTags: 'emotional, powerful, clear, soaring, romantic, dramatic, passionate, heartfelt, nostalgic, classic', lyricsTheme: '사랑의 아름다움과 이별의 아픔', lyricsStyle: '순수하고 진솔한 사랑 표현' },

  // ════════════════════════════════════════
  // ── K-발라드 솔로 거장 ──
  // ════════════════════════════════════════
  { names: ['성시경'], genre: 'K-Lyrical Ballad', mood: 'warm', energy: 'low', bpm: 72, key: 'C', instruments: 'acoustic guitar fingerpicking, grand piano, soft strings, light percussion, warm bass', vocalStyle: 'warm tender male vocal with gentle vibrato and crystal clear tone', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'warm Korean lyrical ballad with acoustic guitar and tender vocal, clean transparent mix', moodTags: 'warm, tender, gentle, romantic, sincere, comforting, nostalgic, acoustic, serene, heartfelt', lyricsTheme: '따뜻한 사랑과 일상의 소소한 행복', lyricsStyle: '서정적이고 따뜻한 표현' },
  { names: ['박효신'], genre: 'K-Art Ballad', mood: 'emotional', energy: 'medium', bpm: 68, key: 'Fm', instruments: 'grand piano, lush orchestral strings, cello, oboe, soft percussion, deep bass', vocalStyle: 'virtuoso male vocal with extraordinary range, emotional belting to delicate pianissimo', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-climax_chorus-outro', ref: 'cinematic Korean art ballad with orchestral grandeur and virtuoso vocal performance', moodTags: 'emotional, dramatic, cinematic, powerful, soaring, majestic, passionate, profound, moving, transcendent', lyricsTheme: '깊은 사랑, 존재의 의미, 영혼의 감동', lyricsStyle: '문학적이고 깊이 있는 표현' },
  { names: ['김범수'], genre: 'K-Power Ballad', mood: 'emotional', energy: 'high', bpm: 75, key: 'Ebm', instruments: 'piano, full orchestra strings, electric guitar solo, powerful drums, bass', vocalStyle: 'explosive male vocal with incredible power and wide vibrato, raspy emotional delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-climax-outro', ref: 'explosive Korean power ballad with full orchestral backing and raw powerful vocal', moodTags: 'powerful, explosive, passionate, dramatic, intense, emotional, raw, soaring, epic, moving', lyricsTheme: '격렬한 사랑과 이별의 고통', lyricsStyle: '강렬하고 직설적인 감정 폭발' },
  { names: ['이수', 'mc the max', 'mc더맥스', 'エムシーザマックス'], genre: 'K-Rock Ballad', mood: 'emotional', energy: 'medium', bpm: 74, key: 'Cm', instruments: 'electric guitar clean arpeggios, piano, strings, powerful drums, bass guitar', vocalStyle: 'high-pitched male vocal with piercing falsetto and emotional rock delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-guitar_solo-final_chorus-outro', ref: 'Korean rock ballad with soaring guitar and piercing high-register vocal', moodTags: 'emotional, soaring, intense, passionate, piercing, dramatic, powerful, yearning, rock, climactic', lyricsTheme: '이별의 고통과 잊을 수 없는 사랑', lyricsStyle: '절절한 감정 토로' },
  { names: ['나얼', 'naul'], genre: 'K-Neo Soul Ballad', mood: 'warm', energy: 'low', bpm: 78, key: 'Db', instruments: 'rhodes piano, warm bass, soft brushed drums, subtle strings, synth pad', vocalStyle: 'silky smooth male vocal with effortless falsetto and soulful runs', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'Korean neo-soul ballad with warm Rhodes and silky smooth vocal, analog warmth', moodTags: 'warm, smooth, soulful, intimate, silky, dreamy, sophisticated, tender, lush, analog', lyricsTheme: '깊은 사랑과 그리움의 감성', lyricsStyle: '감성적이고 은유적인 소울 표현' },
  { names: ['임재범'], genre: 'K-Rock Power Ballad', mood: 'passionate', energy: 'high', bpm: 78, key: 'Em', instruments: 'distorted electric guitar, piano, powerful drums, bass, orchestral strings', vocalStyle: 'raspy powerful male vocal with explosive rock belting and raw emotion', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-guitar_solo-bridge-final_chorus-outro', ref: 'Korean rock power ballad with raw raspy vocal and distorted guitar, 90s rock production', moodTags: 'passionate, raw, powerful, intense, gritty, emotional, rock, explosive, dramatic, heartfelt', lyricsTheme: '격정적인 사랑과 고독, 인생의 아픔', lyricsStyle: '거칠고 직설적인 감정 표현' },
  { names: ['이적'], genre: 'K-Folk Rock Ballad', mood: 'thoughtful', energy: 'medium', bpm: 82, key: 'D', instruments: 'acoustic guitar, electric guitar, piano, bass, drums, strings, harmonica', vocalStyle: 'distinctive warm male vocal with emotional depth and folk sensibility', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'Korean folk-rock ballad with thoughtful lyrics and warm distinctive vocal', moodTags: 'thoughtful, warm, introspective, folk, emotional, sincere, poetic, earthy, deep, comforting', lyricsTheme: '삶의 의미, 위로, 성찰', lyricsStyle: '문학적이고 철학적인 가사' },
  { names: ['김동률'], genre: 'K-Acoustic Ballad', mood: 'nostalgic', energy: 'low', bpm: 75, key: 'G', instruments: 'acoustic guitar, piano, soft strings, gentle percussion, bass, flute', vocalStyle: 'warm emotional male vocal with gentle dynamics and sincere delivery', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'warm Korean acoustic ballad with poetic sensibility and sincere vocal, natural production', moodTags: 'nostalgic, warm, poetic, sincere, gentle, emotional, acoustic, intimate, beautiful, serene', lyricsTheme: '시간의 흐름, 추억, 아름다운 순간들', lyricsStyle: '시적이고 아름다운 서정시' },
  { names: ['윤종신'], genre: 'K-Folk Pop', mood: 'warm', energy: 'low', bpm: 88, key: 'A', instruments: 'acoustic guitar, piano, light bass, gentle drums, strings', vocalStyle: 'conversational warm male vocal with storytelling charm', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'Korean folk pop with storytelling vocal and warm acoustic arrangement', moodTags: 'warm, conversational, nostalgic, gentle, sincere, storytelling, folk, intimate, cozy, reflective', lyricsTheme: '일상의 감성, 사랑, 인생 이야기', lyricsStyle: '스토리텔링 형식의 따뜻한 가사' },
  { names: ['정승환'], genre: 'K-Acoustic Ballad', mood: 'warm', energy: 'low', bpm: 78, key: 'C', instruments: 'acoustic guitar, piano, soft strings, gentle percussion, warm pad', vocalStyle: 'pure clear male vocal with angelic tone and emotional sincerity', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'pure Korean acoustic ballad with angelic clear vocal and gentle arrangement', moodTags: 'warm, pure, angelic, sincere, gentle, comforting, acoustic, emotional, clear, tender', lyricsTheme: '위로, 사랑, 따뜻한 감정', lyricsStyle: '순수하고 진심 어린 감성 표현' },
  { names: ['폴킴', 'paul kim'], genre: 'K-Acoustic Pop Ballad', mood: 'warm', energy: 'low', bpm: 80, key: 'Bb', instruments: 'acoustic guitar, piano, soft bass, gentle drums, light strings', vocalStyle: 'warm husky male vocal with intimate breathy delivery', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'warm Korean acoustic pop ballad with intimate husky vocal and gentle arrangement', moodTags: 'warm, intimate, husky, gentle, romantic, sincere, acoustic, cozy, tender, mellow', lyricsTheme: '사랑, 일상, 따뜻한 감정', lyricsStyle: '일상적이고 따뜻한 감성' },
  { names: ['멜로망스', 'melomance'], genre: 'K-Sweet Ballad', mood: 'warm', energy: 'low', bpm: 76, key: 'F', instruments: 'piano, acoustic guitar, soft strings, light drums, warm bass', vocalStyle: 'sweet clear male duo vocal with bright harmonies and gentle delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'sweet Korean duo ballad with bright clear vocals and warm gentle arrangement', moodTags: 'warm, sweet, bright, gentle, romantic, tender, clear, heartfelt, pure, comforting', lyricsTheme: '사랑의 설렘과 따뜻함', lyricsStyle: '달콤하고 순수한 사랑 표현' },
  { names: ['임한별'], genre: 'K-Emotional Pop Ballad', mood: 'melancholic', energy: 'low', bpm: 70, key: 'Am', instruments: 'piano, strings, acoustic guitar, soft bass, gentle percussion', vocalStyle: 'emotional male vocal with delicate falsetto and tearful delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'emotional Korean pop ballad with tearful vocal and intimate arrangement', moodTags: 'melancholic, emotional, tearful, intimate, tender, bittersweet, yearning, gentle, raw, sincere', lyricsTheme: '이별의 슬픔과 미련', lyricsStyle: '솔직하고 감성적인 이별 표현' },

  // ════════════════════════════════════════
  // ── K-여성 보컬 솔로 ──
  // ════════════════════════════════════════
  { names: ['아이유', 'iu'], genre: 'K-Pop / Acoustic Pop', mood: 'warm', energy: 'medium', bpm: 96, key: 'G', instruments: 'acoustic guitar, piano, light strings, soft drums, ukulele, glockenspiel', vocalStyle: 'sweet clear female vocal with delicate dynamics and breathy intimacy', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus-outro', ref: 'charming Korean acoustic pop with sweet vocal and whimsical arrangement, clean bright mix', moodTags: 'warm, sweet, charming, whimsical, bright, intimate, playful, gentle, dreamy, youthful', lyricsTheme: '사랑, 일상, 감성적 이야기', lyricsStyle: '감성적이고 문학적인 스토리텔링' },
  { names: ['태연', 'taeyeon'], genre: 'K-Pop Ballad / Pop', mood: 'emotional', energy: 'medium', bpm: 82, key: 'Ab', instruments: 'piano, synth strings, soft electronic drums, bass, ambient pad, harp', vocalStyle: 'powerful female vocal with clear tone, emotional belting and airy high notes', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'polished K-pop ballad with powerful female vocal and modern synth-orchestral production', moodTags: 'emotional, powerful, ethereal, dramatic, soaring, polished, modern, airy, cinematic, heartfelt', lyricsTheme: '사랑과 이별, 감정의 깊이', lyricsStyle: '감성적이고 시적인 표현' },
  { names: ['백예린', 'yerin baek'], genre: 'K-Indie R&B / Dream Pop', mood: 'dreamy', energy: 'low', bpm: 88, key: 'Eb', instruments: 'electric guitar with reverb, synth pad, soft drums, bass, ambient textures, rhodes', vocalStyle: 'breathy intimate female vocal with airy falsetto and subtle vibrato', vocalGender: 'f', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'dreamy Korean indie R&B with reverb-soaked guitar and intimate breathy vocal, lo-fi warmth', moodTags: 'dreamy, intimate, airy, ethereal, lo-fi, warm, indie, breathy, atmospheric, gentle', lyricsTheme: '몽환적인 사랑과 내면의 감성', lyricsStyle: '몽환적이고 자유로운 영어/한국어 혼합' },
  { names: ['헤이즈', 'heize'], genre: 'K-R&B / Urban Pop', mood: 'melancholic', energy: 'medium', bpm: 92, key: 'Am', instruments: 'lo-fi piano, trap hi-hats, 808 bass, synth pad, acoustic guitar, soft snare', vocalStyle: 'husky female vocal with emotional rap-singing and breathy delivery', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'modern Korean urban R&B with lo-fi elements, trap-influenced beats and husky female vocal', moodTags: 'melancholic, urban, moody, intimate, lo-fi, bittersweet, modern, atmospheric, raw, emotional', lyricsTheme: '이별 후 감정, 도시적 외로움', lyricsStyle: '솔직하고 일상적인 감정 묘사' },
  { names: ['볼빨간사춘기', 'bol4', 'bolbbalgan4'], genre: 'K-Indie Pop', mood: 'bright', energy: 'medium', bpm: 108, key: 'C', instruments: 'acoustic guitar, bright piano, ukulele, light drums, bass, tambourine', vocalStyle: 'bright youthful female vocal with nasal charm and cheerful delivery', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus-outro', ref: 'bright cheerful Korean indie pop with acoustic guitar and youthful charming vocal', moodTags: 'bright, cheerful, youthful, charming, playful, sweet, fresh, bouncy, warm, indie', lyricsTheme: '첫사랑, 설렘, 풋풋한 감정', lyricsStyle: '귀엽고 솔직한 감정 표현' },
  { names: ['거미', 'gummy'], genre: 'K-Soul Ballad', mood: 'emotional', energy: 'medium', bpm: 70, key: 'Ebm', instruments: 'piano, orchestral strings, acoustic guitar, soft drums, bass, warm pad', vocalStyle: 'powerful soulful female vocal with rich vibrato and emotional depth', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'powerful Korean soul ballad with rich female vocal and cinematic orchestral arrangement', moodTags: 'emotional, powerful, soulful, dramatic, heartfelt, rich, passionate, soaring, cinematic, moving', lyricsTheme: '깊은 사랑과 이별의 고통', lyricsStyle: '감성적이고 강렬한 표현' },
  { names: ['벤', 'ben'], genre: 'K-Pop Ballad', mood: 'emotional', energy: 'low', bpm: 68, key: 'Ab', instruments: 'piano, strings, acoustic guitar, soft bass, gentle drums', vocalStyle: 'clear emotional female vocal with powerful high notes and delicate lower register', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'emotional Korean pop ballad with clear powerful female vocal and gentle arrangement', moodTags: 'emotional, clear, powerful, gentle, tender, heartfelt, dramatic, pure, romantic, moving', lyricsTheme: '사랑과 이별, 간절한 마음', lyricsStyle: '감성적이고 진솔한 가사' },
  { names: ['다비치', 'davichi'], genre: 'K-Pop Ballad Duo', mood: 'emotional', energy: 'medium', bpm: 72, key: 'Cm', instruments: 'piano, orchestral strings, acoustic guitar, bass, drums, cello', vocalStyle: 'powerful female duo vocal with soaring harmonies and emotional dynamics', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'powerful Korean ballad with female duo vocal harmonies and orchestral arrangement', moodTags: 'emotional, powerful, soaring, dramatic, heartfelt, harmonious, passionate, cinematic, moving, rich', lyricsTheme: '사랑과 이별, 그리움', lyricsStyle: '감성적이고 드라마틱한 표현' },
  { names: ['에일리', 'ailee'], genre: 'K-Power Pop / R&B', mood: 'empowering', energy: 'high', bpm: 98, key: 'Bbm', instruments: 'piano, powerful drums, bass, synth, strings, brass stabs', vocalStyle: 'explosive powerful female vocal with R&B runs and belting prowess', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'powerful Korean pop-R&B with explosive female vocal and dynamic arrangement', moodTags: 'empowering, powerful, explosive, fierce, dynamic, passionate, dramatic, confident, soaring, intense', lyricsTheme: '사랑, 이별, 강인한 감정', lyricsStyle: '강렬하고 자신감 있는 감정 표현' },
  { names: ['백지영'], genre: 'K-Pop Ballad / Dance', mood: 'emotional', energy: 'medium', bpm: 82, key: 'Fm', instruments: 'piano, strings, synth, bass, drums, guitar', vocalStyle: 'powerful husky female vocal with emotional intensity and charismatic delivery', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'Korean pop ballad with powerful husky female vocal and polished arrangement', moodTags: 'emotional, powerful, husky, charismatic, dramatic, passionate, intense, heartfelt, fierce, mature', lyricsTheme: '사랑과 이별의 강렬한 감정', lyricsStyle: '강렬하고 성숙한 감정 표현' },
  { names: ['이하이', 'lee hi'], genre: 'K-Soul Pop', mood: 'warm', energy: 'medium', bpm: 85, key: 'Eb', instruments: 'piano, soft bass, gentle drums, strings, synth pad, rhodes', vocalStyle: 'soulful young female vocal with mature tone and emotional depth beyond age', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'Korean soul pop with mature soulful female vocal and warm gentle production', moodTags: 'warm, soulful, mature, gentle, emotional, intimate, smooth, deep, sincere, comforting', lyricsTheme: '사랑, 위로, 감성적 이야기', lyricsStyle: '성숙하고 깊이 있는 감성 표현' },
  { names: ['선미', 'sunmi'], genre: 'K-Pop / Retro Synth Pop', mood: 'moody', energy: 'medium', bpm: 112, key: 'Cm', instruments: 'retro synth, bass, electronic drums, synth pad, vocoder, 80s-style keys', vocalStyle: 'breathy seductive female vocal with retro pop delivery', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'retro-inspired K-pop with 80s synth sounds, moody atmosphere and seductive vocal', moodTags: 'moody, retro, seductive, atmospheric, dark, hypnotic, synth, nocturnal, mysterious, catchy', lyricsTheme: '사랑의 복잡한 감정, 중독적 매력', lyricsStyle: '몽환적이고 중독적인 표현' },
  { names: ['청하', 'chungha'], genre: 'K-Pop / Latin Pop', mood: 'fierce', energy: 'high', bpm: 118, key: 'Am', instruments: 'Latin guitar, synth bass, dance beat, brass, electronic percussion, strings', vocalStyle: 'powerful female vocal with dance pop delivery and Latin flair', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-dance_break-final_chorus-outro', ref: 'fierce K-pop dance track with Latin influence, powerful vocal and choreography-driven energy', moodTags: 'fierce, powerful, Latin, danceable, sexy, confident, dynamic, rhythmic, bold, hot', lyricsTheme: '자신감, 사랑, 매력', lyricsStyle: '강렬하고 자신감 넘치는 표현' },
  { names: ['비비', 'bibi'], genre: 'K-Alternative Pop / R&B', mood: 'quirky', energy: 'medium', bpm: 100, key: 'Gm', instruments: 'quirky synth, lo-fi beats, bass, vintage samples, vocal effects, piano', vocalStyle: 'distinctive female vocal with quirky personality and genre-fluid delivery', vocalGender: 'f', structure: 'intro-verse-chorus-verse-chorus-bridge-outro', ref: 'quirky Korean alternative pop with unique personality, genre-bending production and distinctive vocal', moodTags: 'quirky, unique, playful, edgy, genre-bending, experimental, catchy, bold, artistic, fresh', lyricsTheme: '자유분방한 감성, 독특한 시선', lyricsStyle: '독특하고 자유분방한 표현' },
  { names: ['수지', 'suzy', '배수지'], genre: 'K-Pop / Soft Pop', mood: 'sweet', energy: 'low', bpm: 85, key: 'F', instruments: 'acoustic guitar, piano, soft strings, gentle drums, bass', vocalStyle: 'sweet soft female vocal with innocent charm and gentle delivery', vocalGender: 'f', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'sweet Korean soft pop with gentle arrangement and innocent charming vocal', moodTags: 'sweet, innocent, gentle, warm, charming, soft, romantic, pure, bright, tender', lyricsTheme: '순수한 사랑, 설렘', lyricsStyle: '순수하고 달콤한 감성' },

  // ════════════════════════════════════════
  // ── K-Hip-Hop / K-R&B 현대 ──
  // ════════════════════════════════════════
  { names: ['crush', '크러쉬'], genre: 'K-R&B / Urban', mood: 'sensual', energy: 'medium', bpm: 95, key: 'Bbm', instruments: 'synth bass, lo-fi keys, trap hi-hats, ambient pad, vocal layers, soft 808', vocalStyle: 'smooth male R&B vocal with airy falsetto and melodic delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'modern Korean R&B with smooth production, lo-fi textures and silky male vocal', moodTags: 'smooth, sensual, urban, modern, silky, atmospheric, chill, warm, groovy, laid-back', lyricsTheme: '사랑의 감정, 로맨틱한 분위기', lyricsStyle: '세련되고 로맨틱한 표현' },
  { names: ['dean', '딘'], genre: 'K-Alternative R&B', mood: 'moody', energy: 'medium', bpm: 100, key: 'Fm', instruments: 'detuned synth, glitchy percussion, deep bass, ambient texture, filtered vocal chops', vocalStyle: 'experimental male vocal with falsetto, vocal processing and fluid dynamics', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-outro', ref: 'experimental Korean alternative R&B with glitchy production and genre-bending sound design', moodTags: 'moody, experimental, atmospheric, dark, fluid, innovative, edgy, hypnotic, alternative, textured', lyricsTheme: '복잡한 감정과 현대적 사랑', lyricsStyle: '실험적이고 자유로운 표현' },
  { names: ['자이언티', 'zion.t', 'zion t'], genre: 'K-R&B / Neo Soul', mood: 'laid-back', energy: 'low', bpm: 88, key: 'Eb', instruments: 'vintage keys, warm bass, lo-fi drums, vinyl texture, subtle synth, guitar', vocalStyle: 'nasal distinctive male vocal with laid-back delivery and melodic charm', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-outro', ref: 'retro-tinged Korean neo-soul with vintage keys and distinctive nasal vocal, warm lo-fi production', moodTags: 'laid-back, retro, warm, charming, vintage, smooth, quirky, mellow, soulful, intimate', lyricsTheme: '일상의 감성, 위트 있는 사랑 이야기', lyricsStyle: '위트 있고 독특한 감성 표현' },
  { names: ['에픽하이', 'epik high'], genre: 'K-Hip-Hop / Alternative', mood: 'thoughtful', energy: 'medium', bpm: 95, key: 'Am', instruments: 'piano, acoustic guitar, lo-fi beats, strings, turntable scratches, deep bass', vocalStyle: 'introspective male rap with melodic hooks and spoken-word passages', vocalGender: 'm', structure: 'intro-verse-hook-verse-hook-bridge-hook-outro', ref: 'thoughtful Korean alternative hip-hop with poetic lyrics and genre-blending production', moodTags: 'thoughtful, introspective, poetic, alternative, deep, atmospheric, emotional, literary, hybrid, artistic', lyricsTheme: '삶의 의미, 사회 비판, 깊은 성찰', lyricsStyle: '문학적이고 철학적인 가사' },
  { names: ['지코', 'zico'], genre: 'K-Hip-Hop / Pop Rap', mood: 'energetic', energy: 'high', bpm: 130, key: 'Cm', instruments: 'heavy 808, trap hi-hats, synth lead, bass drop, vocal chops, brass', vocalStyle: 'charismatic male rap with melodic hooks and versatile flow', vocalGender: 'm', structure: 'intro-verse-hook-verse-hook-bridge-hook-outro', ref: 'Korean pop-rap with catchy hooks, heavy 808 beats and charismatic delivery', moodTags: 'energetic, charismatic, catchy, bold, fun, confident, groovy, hard-hitting, playful, dynamic', lyricsTheme: '자신감, 성공, 즐거움', lyricsStyle: '위트 있고 자신감 넘치는 래핑' },
  { names: ['빈지노', 'beenzino'], genre: 'K-Hip-Hop / Smooth Rap', mood: 'laid-back', energy: 'medium', bpm: 95, key: 'Eb', instruments: 'smooth bass, jazz piano, lo-fi drums, synth pad, subtle guitar', vocalStyle: 'smooth laid-back male rap with jazz-influenced flow and melodic hooks', vocalGender: 'm', structure: 'intro-verse-hook-verse-hook-bridge-outro', ref: 'smooth Korean hip-hop with jazz influence, laid-back flow and sophisticated production', moodTags: 'laid-back, smooth, jazzy, sophisticated, cool, chill, confident, stylish, mellow, groovy', lyricsTheme: '일상, 사랑, 자유로운 라이프스타일', lyricsStyle: '세련되고 여유로운 표현' },
  { names: ['박재범', 'jay park'], genre: 'K-Hip-Hop / R&B', mood: 'groovy', energy: 'high', bpm: 105, key: 'Am', instruments: 'trap beats, 808 bass, synth, R&B keys, hi-hats, vocal processing', vocalStyle: 'versatile male vocal with R&B singing and rap switching, auto-tune flair', vocalGender: 'm', structure: 'intro-verse-hook-verse-hook-bridge-hook-outro', ref: 'Korean hip-hop R&B hybrid with trap influence, versatile vocal delivery and Western-influenced production', moodTags: 'groovy, confident, sexy, urban, modern, versatile, slick, bold, trendy, energetic', lyricsTheme: '사랑, 자신감, 파티 분위기', lyricsStyle: '영어/한국어 혼합, 자유분방한 표현' },
  { names: ['쇼미더머니', 'show me the money', '래퍼'], genre: 'K-Hip-Hop / Trap', mood: 'aggressive', energy: 'very high', bpm: 145, key: 'Cm', instruments: 'heavy 808, dark synth, trap hi-hats, bass drops, vocal ad-libs, siren sounds', vocalStyle: 'aggressive male rap with fast flow and hard-hitting delivery', vocalGender: 'm', structure: 'intro-verse-hook-verse-hook-verse-hook-outro', ref: 'aggressive Korean trap hip-hop with heavy bass, dark production and fierce rap delivery', moodTags: 'aggressive, hard-hitting, dark, fierce, intense, raw, bold, powerful, trap, heavy', lyricsTheme: '실력 과시, 성공, 자부심', lyricsStyle: '공격적이고 자신감 있는 래핑' },
  { names: ['이센스', 'e-sens'], genre: 'K-Boom Bap Hip-Hop', mood: 'thoughtful', energy: 'medium', bpm: 90, key: 'Dm', instruments: 'boom bap drums, jazz samples, vinyl scratches, deep bass, piano loops', vocalStyle: 'lyrical male rap with thoughtful flow and old-school sensibility', vocalGender: 'm', structure: 'intro-verse-hook-verse-hook-verse-outro', ref: 'Korean boom bap hip-hop with jazz samples, old-school beats and lyrical rap delivery', moodTags: 'thoughtful, lyrical, old-school, jazzy, deep, authentic, raw, poetic, boom-bap, classic', lyricsTheme: '삶의 고뇌, 진정성, 자아 성찰', lyricsStyle: '리리컬하고 깊이 있는 가사' },
  { names: ['다이나믹듀오', 'dynamic duo'], genre: 'K-Hip-Hop / Pop Rap', mood: 'groovy', energy: 'medium', bpm: 100, key: 'Bb', instruments: 'funky bass, synth, drums, piano, brass stabs, vocal samples', vocalStyle: 'male duo rap with contrasting flows and catchy melodic hooks', vocalGender: 'm', structure: 'intro-verse-hook-verse-hook-bridge-hook-outro', ref: 'Korean pop-hip-hop with funky grooves, catchy hooks and contrasting duo rap styles', moodTags: 'groovy, fun, catchy, cool, confident, playful, smooth, dynamic, retro, upbeat', lyricsTheme: '사랑, 일상, 유쾌한 이야기', lyricsStyle: '재치 있고 유쾌한 가사' },
  { names: ['ph-1', 'pH-1'], genre: 'K-Hip-Hop / Chill Rap', mood: 'chill', energy: 'medium', bpm: 98, key: 'Eb', instruments: 'lo-fi beats, smooth bass, synth pad, ambient textures, soft drums', vocalStyle: 'smooth bilingual male rap with melodic hooks and chill delivery', vocalGender: 'm', structure: 'intro-verse-hook-verse-hook-bridge-outro', ref: 'chill Korean hip-hop with smooth bilingual rap, lo-fi production and laid-back vibe', moodTags: 'chill, smooth, bilingual, laid-back, cool, modern, atmospheric, mellow, stylish, urban', lyricsTheme: '사랑, 일상, 감성적 이야기', lyricsStyle: '영어/한국어 혼합, 감성적 표현' },

  // ════════════════════════════════════════
  // ── K-Pop 아이돌 그룹 ──
  // ════════════════════════════════════════
  { names: ['bts', '방탄소년단', 'bangtan'], genre: 'K-Pop / Hip-Hop Pop', mood: 'energetic', energy: 'high', bpm: 120, key: 'Fm', instruments: 'synth brass, trap 808, hi-hat rolls, EDM synth, vocal chops, strings, bass drop', vocalStyle: 'dynamic male group vocal with rap verses and powerful vocal chorus', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-rap-prechorus-chorus-bridge-dance_break-final_chorus-outro', ref: 'high-energy K-pop with hip-hop elements, powerful choreography-driven arrangement, polished modern production', moodTags: 'energetic, powerful, anthemic, dynamic, youthful, inspirational, bold, fierce, polished, stadium', lyricsTheme: '자기 성장, 청춘, 꿈과 도전', lyricsStyle: '진솔한 메시지와 위트 있는 워드플레이' },
  { names: ['blackpink', '블랙핑크'], genre: 'K-Pop / EDM Pop', mood: 'fierce', energy: 'very high', bpm: 130, key: 'Cm', instruments: 'heavy 808 bass, trap hi-hats, brass stabs, synth drops, whistle synth, hard-hitting kicks', vocalStyle: 'fierce female group vocal with rap swag and powerful high notes', vocalGender: 'f', structure: 'intro-verse-prechorus-drop_chorus-verse-rap-prechorus-drop_chorus-bridge-final_chorus-outro', ref: 'fierce K-pop girl crush with heavy bass drops and EDM-trap hybrid production', moodTags: 'fierce, powerful, bold, confident, edgy, glamorous, hard-hitting, anthemic, bass-heavy, intense', lyricsTheme: '자신감, 독립, 강인한 여성상', lyricsStyle: '강렬하고 자신감 넘치는 표현' },
  { names: ['newjeans', '뉴진스'], genre: 'K-Pop / Y2K Pop', mood: 'fresh', energy: 'medium', bpm: 110, key: 'G', instruments: 'jersey club beats, soft synth, vintage samples, light 808, airy pad, pluck synth', vocalStyle: 'sweet youthful female vocal with soft delivery and catchy melodic hooks', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'retro Y2K-inspired K-pop with jersey club influence, minimalist production and catchy hooks', moodTags: 'fresh, youthful, retro, catchy, minimalist, playful, trendy, breezy, nostalgic, bright', lyricsTheme: '풋풋한 사랑, 설렘, 청춘', lyricsStyle: '심플하고 캐치한 표현' },
  { names: ['aespa', '에스파'], genre: 'K-Pop / Hyperpop', mood: 'futuristic', energy: 'very high', bpm: 135, key: 'Dm', instruments: 'glitch synth, heavy bass, distorted leads, 808, industrial percussion, vocal processing', vocalStyle: 'processed female group vocal with powerful belting and electronic manipulation', vocalGender: 'f', structure: 'intro-verse-prechorus-drop-verse-prechorus-drop-bridge-breakdown-final_drop-outro', ref: 'futuristic K-pop with hyperpop elements, maximalist production and genre-bending arrangement', moodTags: 'futuristic, intense, maximalist, electronic, bold, experimental, powerful, cyberpunk, dynamic, cutting-edge', lyricsTheme: '가상세계, 정체성, 미래적 서사', lyricsStyle: '세계관 기반 스토리텔링' },
  { names: ['ive', '아이브'], genre: 'K-Pop / Teen Fresh', mood: 'confident', energy: 'high', bpm: 116, key: 'Bb', instruments: 'bright synth, punchy bass, dance beat, strings, brass, vocal chops', vocalStyle: 'confident female group vocal with bright tone and catchy hooks', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'confident K-pop with bright teen-fresh production, catchy hooks and polished arrangement', moodTags: 'confident, bright, catchy, glamorous, polished, youthful, fun, chic, energetic, anthemic', lyricsTheme: '자신감, 사랑, 긍정적 에너지', lyricsStyle: '밝고 자신감 넘치는 표현' },
  { names: ['seventeen', '세븐틴'], genre: 'K-Pop / Performance Pop', mood: 'energetic', energy: 'high', bpm: 122, key: 'Ab', instruments: 'synth, punchy drums, bass, piano, strings, EDM elements, guitar riff', vocalStyle: 'versatile male group vocal with rap line and powerful vocal line', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-rap-chorus-bridge-dance_break-final_chorus-outro', ref: 'self-produced K-pop with dynamic arrangement, balanced rap-vocal structure and performance focus', moodTags: 'energetic, dynamic, youthful, powerful, versatile, anthemic, bright, polished, fun, groovy', lyricsTheme: '청춘, 사랑, 우정, 성장', lyricsStyle: '밝고 진솔한 감성 표현' },
  { names: ['stray kids', '스트레이 키즈', '스키즈'], genre: 'K-Pop / EDM Hip-Hop', mood: 'intense', energy: 'very high', bpm: 140, key: 'Cm', instruments: 'distorted bass, heavy 808, industrial synth, aggressive drums, vocal distortion, brass', vocalStyle: 'aggressive male group vocal with intense rap and powerful belting', vocalGender: 'm', structure: 'intro-verse-buildup-drop-verse-rap-drop-bridge-breakdown-final_drop-outro', ref: 'hard-hitting K-pop with EDM drops, aggressive hip-hop elements and intense performance energy', moodTags: 'intense, aggressive, powerful, hard-hitting, dark, fierce, energetic, raw, bold, explosive', lyricsTheme: '자유, 반항, 자기 정체성', lyricsStyle: '강렬하고 직설적인 메시지' },
  { names: ['exo', '엑소'], genre: 'K-Pop / R&B Pop', mood: 'smooth', energy: 'high', bpm: 112, key: 'Fm', instruments: 'synth pad, R&B bass, crisp drums, piano, strings, electronic elements', vocalStyle: 'powerful male group vocal with R&B harmonies and strong high notes', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'polished K-pop with R&B foundation, powerful vocal harmonies and sleek production', moodTags: 'smooth, powerful, polished, sophisticated, dynamic, romantic, sleek, groovy, anthemic, rich', lyricsTheme: '사랑, 그리움, 로맨틱한 감정', lyricsStyle: '로맨틱하고 세련된 표현' },
  { names: ['twice', '트와이스'], genre: 'K-Pop / Bright Pop', mood: 'cheerful', energy: 'high', bpm: 118, key: 'C', instruments: 'bright synth, funky bass, dance beat, brass, strings, electronic piano', vocalStyle: 'sweet cheerful female group vocal with catchy hook and bright tone', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'bright cheerful K-pop with catchy hook-driven production and sweet vocal delivery', moodTags: 'cheerful, bright, catchy, sweet, playful, energetic, fun, bubbly, youthful, danceable', lyricsTheme: '설렘, 사랑, 밝은 감정', lyricsStyle: '밝고 귀여운 감성 표현' },
  { names: ['red velvet', '레드벨벳'], genre: 'K-Pop / Experimental Pop', mood: 'quirky', energy: 'high', bpm: 120, key: 'F', instruments: 'quirky synth, bass, electronic drums, strings, retro samples, vocal layers', vocalStyle: 'sweet yet versatile female group vocal with quirky charm and powerful moments', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'experimental K-pop with dual concept (Red: bright pop / Velvet: smooth R&B), quirky production', moodTags: 'quirky, sweet, experimental, bright, playful, sophisticated, retro, catchy, versatile, fun', lyricsTheme: '사랑, 호기심, 독특한 이야기', lyricsStyle: '독특하고 중독적인 표현' },
  { names: ['(g)i-dle', '여자아이들', 'gidle', 'g idle'], genre: 'K-Pop / Dark Pop', mood: 'fierce', energy: 'high', bpm: 125, key: 'Cm', instruments: 'dark synth, heavy bass, tribal drums, brass, electronic elements, guitar riff', vocalStyle: 'powerful female group vocal with fierce rap and distinctive husky lead vocal', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-rap-chorus-bridge-final_chorus-outro', ref: 'self-produced K-pop with dark fierce concept, powerful vocals and genre-blending production', moodTags: 'fierce, dark, powerful, bold, confident, edgy, charismatic, intense, unique, commanding', lyricsTheme: '자신감, 독립, 파워풀한 여성상', lyricsStyle: '강렬하고 독특한 표현' },
  { names: ['le sserafim', '르세라핌'], genre: 'K-Pop / EDM Pop', mood: 'confident', energy: 'high', bpm: 118, key: 'Dm', instruments: 'deep bass, synth, dance beat, vocal processing, minimal percussion, ambient pad', vocalStyle: 'confident female group vocal with modern breathy delivery and powerful drops', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'modern K-pop with EDM elements, confident concept and sleek minimalist production', moodTags: 'confident, sleek, modern, powerful, cool, fierce, minimalist, bold, stylish, dynamic', lyricsTheme: '자신감, 도전, 두려움 없는 전진', lyricsStyle: '당당하고 모던한 표현' },
  { names: ['nct', 'nct 127', 'nct dream', '엔시티'], genre: 'K-Pop / Neo Pop', mood: 'intense', energy: 'very high', bpm: 132, key: 'Em', instruments: 'experimental synth, heavy bass, glitch elements, 808, industrial sounds, strings', vocalStyle: 'dynamic male group vocal with powerful rap and diverse vocal textures', vocalGender: 'm', structure: 'intro-verse-prechorus-drop-verse-rap-drop-bridge-breakdown-final_drop-outro', ref: 'experimental K-pop with neo-culture concept, genre-blending production and dynamic performance', moodTags: 'intense, experimental, dynamic, futuristic, powerful, edgy, innovative, bold, complex, electrifying', lyricsTheme: '자유, 새로운 세계, 청춘의 에너지', lyricsStyle: '실험적이고 감각적인 표현' },
  { names: ['got7', '갓세븐'], genre: 'K-Pop / Hip-Hop Pop', mood: 'groovy', energy: 'high', bpm: 115, key: 'Am', instruments: 'funky bass, synth, drums, brass, vocal chops, guitar, trap elements', vocalStyle: 'charismatic male group vocal with smooth rap and powerful singing', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-rap-chorus-bridge-final_chorus-outro', ref: 'groovy K-pop with hip-hop influence, charismatic delivery and funky production', moodTags: 'groovy, charismatic, fun, confident, smooth, dynamic, catchy, cool, playful, energetic', lyricsTheme: '사랑, 자신감, 즐거움', lyricsStyle: '재치 있고 매력적인 표현' },
  { names: ['shinee', '샤이니'], genre: 'K-Pop / Funk Pop', mood: 'groovy', energy: 'high', bpm: 122, key: 'Bb', instruments: 'funky guitar, synth bass, electronic drums, brass, strings, retro synth', vocalStyle: 'versatile male group vocal with powerful lead and funky delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-dance_break-final_chorus-outro', ref: 'trend-setting K-pop with funk-pop influence, sophisticated arrangement and powerful vocals', moodTags: 'groovy, sophisticated, dynamic, trendy, funky, powerful, catchy, polished, innovative, bright', lyricsTheme: '사랑, 매력, 트렌디한 감성', lyricsStyle: '세련되고 트렌디한 표현' },
  { names: ['mamamoo', '마마무'], genre: 'K-Pop / Retro Soul', mood: 'empowering', energy: 'high', bpm: 110, key: 'Gm', instruments: 'brass, funky guitar, bass, drums, retro organ, clap, synth', vocalStyle: 'powerful female group vocal with exceptional harmonies and soulful delivery', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'retro soul-influenced K-pop with powerful vocal harmonies and live band feel', moodTags: 'empowering, soulful, powerful, retro, funky, confident, dynamic, groovy, bold, fun', lyricsTheme: '자신감, 사랑, 즐거움', lyricsStyle: '파워풀하고 유쾌한 표현' },
  { names: ['itzy', '있지'], genre: 'K-Pop / Teen Crush', mood: 'confident', energy: 'very high', bpm: 125, key: 'Fm', instruments: 'heavy bass, synth, electronic drums, whistle synth, brass stabs, guitar riff', vocalStyle: 'energetic female group vocal with fierce delivery and powerful hooks', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-dance_break-final_chorus-outro', ref: 'high-energy K-pop teen crush with powerful beats, fierce delivery and dance-driven arrangement', moodTags: 'confident, fierce, energetic, bold, powerful, fun, catchy, dynamic, youthful, explosive', lyricsTheme: '자기 확신, 자유, 당당함', lyricsStyle: '당당하고 에너지 넘치는 표현' },
  { names: ['ateez', '에이티즈'], genre: 'K-Pop / Epic Pop', mood: 'epic', energy: 'very high', bpm: 135, key: 'Dm', instruments: 'orchestral hits, heavy drums, synth, brass, chanting vocals, 808 bass', vocalStyle: 'powerful male group vocal with theatrical delivery and fierce energy', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-rap-chorus-bridge-breakdown-final_chorus-outro', ref: 'epic theatrical K-pop with orchestral elements, powerful performance energy and pirate concept', moodTags: 'epic, powerful, theatrical, intense, anthemic, fierce, dynamic, bold, dramatic, commanding', lyricsTheme: '모험, 꿈, 자유를 향한 항해', lyricsStyle: '서사적이고 웅장한 표현' },
  { names: ['treasure', '트레저'], genre: 'K-Pop / Bright Hip-Hop Pop', mood: 'energetic', energy: 'high', bpm: 118, key: 'C', instruments: 'bright synth, punchy drums, bass, brass, vocal chops, guitar', vocalStyle: 'youthful male group vocal with bright harmonies and energetic rap', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-rap-chorus-bridge-final_chorus-outro', ref: 'bright energetic K-pop with youthful charm, catchy hooks and hip-hop elements', moodTags: 'energetic, bright, youthful, catchy, fun, cheerful, dynamic, fresh, playful, bold', lyricsTheme: '청춘, 사랑, 즐거움', lyricsStyle: '밝고 에너지 넘치는 표현' },
  { names: ['enhypen', '엔하이픈'], genre: 'K-Pop / Dark Pop', mood: 'dark', energy: 'high', bpm: 128, key: 'Cm', instruments: 'dark synth, heavy bass, electronic drums, strings, atmospheric pad, piano', vocalStyle: 'mysterious male group vocal with dark charm and powerful moments', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'dark atmospheric K-pop with vampire/dark concept, mysterious production and powerful delivery', moodTags: 'dark, mysterious, atmospheric, powerful, intense, moody, elegant, dramatic, haunting, sleek', lyricsTheme: '어둠, 유혹, 초자연적 서사', lyricsStyle: '미스터리하고 세계관 중심의 가사' },
  { names: ['txt', '투모로우바이투게더', 'tomorrow x together'], genre: 'K-Pop / Emo Pop', mood: 'emotional', energy: 'high', bpm: 125, key: 'Am', instruments: 'electric guitar, synth, bass, drums, piano, ambient pad, vocal layers', vocalStyle: 'emotional male group vocal with emo-pop sensibility and youthful energy', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'genre-blending K-pop with emo-pop rock influence, emotional storytelling and youthful energy', moodTags: 'emotional, youthful, emo, energetic, dramatic, dreamy, alternative, catchy, dynamic, bittersweet', lyricsTheme: '성장통, 청춘의 혼란, 꿈과 현실', lyricsStyle: '감성적이고 성장 서사 중심' },
  { names: ['소녀시대', 'girls generation', 'snsd'], genre: 'K-Pop / Synth Pop', mood: 'bright', energy: 'high', bpm: 120, key: 'F', instruments: 'synth, bass, dance beat, strings, vocal harmonies, electronic piano, clap', vocalStyle: 'bright sweet female group vocal with iconic chorus harmonies', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'iconic K-pop with bright synth-pop production, legendary chorus hooks and sweet group vocal', moodTags: 'bright, iconic, sweet, energetic, catchy, cheerful, legendary, fun, glamorous, anthemic', lyricsTheme: '사랑, 소녀의 꿈, 설렘', lyricsStyle: '밝고 사랑스러운 표현' },
  { names: ['2ne1', '투애니원'], genre: 'K-Pop / Hip-Hop EDM', mood: 'fierce', energy: 'very high', bpm: 130, key: 'Cm', instruments: 'heavy synth, bass drop, 808, electronic drums, brass, vocal processing', vocalStyle: 'fierce female group vocal with powerful rap and explosive singing', vocalGender: 'f', structure: 'intro-verse-prechorus-drop_chorus-verse-rap-drop_chorus-bridge-final_chorus-outro', ref: 'pioneering K-pop girl crush with EDM-hip-hop production and fierce energy', moodTags: 'fierce, powerful, iconic, bold, explosive, energetic, edgy, confident, trailblazing, intense', lyricsTheme: '독립, 자신감, 강인한 여성', lyricsStyle: '강렬하고 파워풀한 표현' },
  { names: ['bigbang', '빅뱅'], genre: 'K-Pop / Hip-Hop EDM', mood: 'innovative', energy: 'high', bpm: 125, key: 'Am', instruments: 'synth, heavy bass, electronic drums, guitar, vocal processing, brass', vocalStyle: 'diverse male group vocal with distinctive individual tones, rap and powerful singing', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-rap-chorus-bridge-final_chorus-outro', ref: 'genre-defining K-pop with hip-hop and EDM fusion, iconic production and diverse vocal colors', moodTags: 'innovative, iconic, diverse, powerful, charismatic, edgy, trendsetting, dynamic, cool, anthemic', lyricsTheme: '사랑, 파티, 감성', lyricsStyle: '다양하고 아이코닉한 표현' },
  { names: ['winner', '위너'], genre: 'K-Pop / Chill Pop', mood: 'bright', energy: 'medium', bpm: 108, key: 'G', instruments: 'acoustic guitar, synth, bass, light drums, piano, tropical elements', vocalStyle: 'warm male group vocal with laid-back charm and melodic delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'bright chill K-pop with tropical influence, warm vocal delivery and feel-good production', moodTags: 'bright, chill, warm, breezy, tropical, fun, laid-back, summery, catchy, cheerful', lyricsTheme: '사랑, 여름, 즐거운 일상', lyricsStyle: '밝고 여유로운 감성 표현' },
  { names: ['ikon', '아이콘'], genre: 'K-Pop / Hip-Hop Pop', mood: 'energetic', energy: 'high', bpm: 122, key: 'Fm', instruments: 'trap beats, synth, bass, electronic drums, brass, vocal chops', vocalStyle: 'energetic male group vocal with powerful rap and emotional singing', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-rap-chorus-bridge-final_chorus-outro', ref: 'energetic K-pop with strong hip-hop roots, powerful delivery and emotional versatility', moodTags: 'energetic, powerful, emotional, dynamic, hip-hop, versatile, anthemic, youthful, bold, passionate', lyricsTheme: '사랑, 청춘, 열정', lyricsStyle: '열정적이고 감성적인 표현' },

  // ════════════════════════════════════════
  // ── K-밴드 / K-록 ──
  // ════════════════════════════════════════
  { names: ['넬', 'nell'], genre: 'K-Alternative Rock / Emo', mood: 'melancholic', energy: 'medium', bpm: 92, key: 'Am', instruments: 'clean electric guitar, delay guitar, bass, steady drums, ambient synth, piano', vocalStyle: 'delicate male vocal with emotional fragility and ethereal quality', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'atmospheric Korean alternative rock with ethereal guitars and emotionally fragile vocal', moodTags: 'melancholic, atmospheric, ethereal, fragile, dreamy, alternative, introspective, poetic, ambient, delicate', lyricsTheme: '상실, 그리움, 존재의 고독', lyricsStyle: '시적이고 은유적인 감성 표현' },
  { names: ['잔나비', 'jannabi'], genre: 'K-Retro Rock / Indie', mood: 'nostalgic', energy: 'medium', bpm: 105, key: 'D', instruments: 'vintage electric guitar, organ, bass, retro drums, tambourine, brass section', vocalStyle: 'warm retro male vocal with vintage charm and expressive dynamics', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-guitar_solo-chorus-outro', ref: 'Korean retro rock with 70s-80s vintage sound, warm analog production and nostalgic charm', moodTags: 'nostalgic, retro, warm, vintage, charming, romantic, groovy, organic, breezy, cheerful', lyricsTheme: '사랑, 청춘, 아름다운 순간들', lyricsStyle: '레트로 감성의 로맨틱한 표현' },
  { names: ['day6', '데이식스'], genre: 'K-Pop Rock / Band', mood: 'energetic', energy: 'high', bpm: 118, key: 'E', instruments: 'electric guitar, acoustic guitar, bass, drums, keyboard, synthesizer', vocalStyle: 'passionate male vocal with rock energy and melodic pop sensibility', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'Korean pop-rock band with catchy melodies, driving guitar and passionate vocal delivery', moodTags: 'energetic, passionate, catchy, driving, youthful, emotional, rock, anthemic, bright, dynamic', lyricsTheme: '사랑, 이별, 청춘의 감정', lyricsStyle: '직설적이고 감성적인 표현' },
  { names: ['10cm', '십센치'], genre: 'K-Acoustic Pop / Indie', mood: 'warm', energy: 'low', bpm: 95, key: 'G', instruments: 'acoustic guitar, light piano, soft drums, bass, subtle strings', vocalStyle: 'high-pitched distinctive male vocal with nasally charm and indie sensibility', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'Korean acoustic indie pop with distinctive high male vocal and warm guitar-driven arrangement', moodTags: 'warm, indie, charming, acoustic, gentle, quirky, bright, romantic, cozy, sincere', lyricsTheme: '사랑, 일상의 감성, 솔직한 고백', lyricsStyle: '위트 있고 솔직한 감성 표현' },
  { names: ['hyukoh', '혁오'], genre: 'K-Indie Rock / Psychedelic', mood: 'dreamy', energy: 'medium', bpm: 100, key: 'Em', instruments: 'reverb guitar, bass, drums, synth, ambient textures, vintage keys', vocalStyle: 'distinctive breathy male vocal with indie charm and psychedelic delivery', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-outro', ref: 'Korean indie psychedelic rock with dreamy reverb guitars and distinctive breathy vocal', moodTags: 'dreamy, psychedelic, indie, atmospheric, unique, artistic, hazy, vintage, cool, ethereal', lyricsTheme: '일상의 관조, 자유, 독특한 시선', lyricsStyle: '독특하고 예술적인 감성' },
  { names: ['실리카겔', 'silica gel'], genre: 'K-Indie / Synth Rock', mood: 'experimental', energy: 'high', bpm: 128, key: 'Dm', instruments: 'synth, distorted bass, electronic drums, electric guitar, ambient pad, vocoder', vocalStyle: 'experimental male vocal with synth processing and genre-fluid delivery', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-outro', ref: 'experimental Korean synth rock with electronic elements, genre-bending production', moodTags: 'experimental, electronic, innovative, edgy, dynamic, futuristic, artistic, bold, unique, hypnotic', lyricsTheme: '실험적 감성, 디지털 시대의 감정', lyricsStyle: '실험적이고 추상적인 표현' },
  { names: ['yb', '윤도현밴드', '윤도현'], genre: 'K-Rock', mood: 'passionate', energy: 'very high', bpm: 135, key: 'Em', instruments: 'heavy electric guitar, bass guitar, powerful drums, rhythm guitar, occasional brass', vocalStyle: 'powerful raspy male rock vocal with explosive energy and raw emotion', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-guitar_solo-final_chorus-outro', ref: 'powerful Korean rock with heavy guitar riffs, driving drums and explosive vocal energy', moodTags: 'passionate, powerful, raw, intense, rock, explosive, energetic, driving, fierce, anthemic', lyricsTheme: '열정, 자유, 삶의 에너지', lyricsStyle: '열정적이고 직설적인 록 가사' },
  { names: ['busker busker', '버스커 버스커'], genre: 'K-Acoustic Folk Pop', mood: 'bright', energy: 'medium', bpm: 108, key: 'G', instruments: 'acoustic guitar, cajon, bass, harmonica, light percussion, ukulele', vocalStyle: 'warm cheerful male vocal with folk charm and bright delivery', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'bright Korean acoustic folk pop with cheerful guitar and warm sing-along quality', moodTags: 'bright, cheerful, warm, folk, acoustic, sunny, breezy, heartfelt, sing-along, organic', lyricsTheme: '봄, 사랑, 밝은 일상', lyricsStyle: '밝고 따뜻한 감성 표현' },
  { names: ['체리필터', 'cherry filter'], genre: 'K-Rock / Punk', mood: 'energetic', energy: 'very high', bpm: 145, key: 'Am', instruments: 'distorted guitar, bass, fast drums, punk energy, occasional synth', vocalStyle: 'fierce female rock vocal with punk attitude and powerful delivery', vocalGender: 'f', structure: 'intro-verse-chorus-verse-chorus-bridge-final_chorus-outro', ref: 'Korean punk rock with fierce female vocal, fast tempo and rebellious energy', moodTags: 'energetic, fierce, punk, rebellious, powerful, raw, fast, driving, intense, fun', lyricsTheme: '자유, 반항, 에너지', lyricsStyle: '직설적이고 반항적인 표현' },

  // ════════════════════════════════════════
  // ── K-Indie / K-Folk ──
  // ════════════════════════════════════════
  { names: ['악동뮤지션', 'akmu', 'akdong musician'], genre: 'K-Indie Pop / Folk Pop', mood: 'bright', energy: 'medium', bpm: 112, key: 'D', instruments: 'acoustic guitar, piano, bright drums, bass, ukulele, handclaps', vocalStyle: 'bright sibling duo vocal with youthful harmony and distinctive tone', vocalGender: 'mixed', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus-outro', ref: 'bright Korean indie-pop with sibling vocal harmony and folk-influenced acoustic production', moodTags: 'bright, youthful, fresh, quirky, playful, warm, indie, acoustic, charming, creative', lyricsTheme: '일상, 사랑, 독특한 시선의 이야기', lyricsStyle: '창의적이고 독특한 스토리텔링' },
  { names: ['아이오아이', 'i.o.i', 'ioi'], genre: 'K-Pop / Fresh Pop', mood: 'bright', energy: 'high', bpm: 116, key: 'C', instruments: 'bright synth, bass, dance beat, strings, piano, handclaps', vocalStyle: 'sweet youthful female group vocal with fresh charm', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'bright fresh K-pop with youthful charm, catchy melodies and sweet group vocals', moodTags: 'bright, fresh, youthful, catchy, sweet, fun, cheerful, charming, energetic, innocent', lyricsTheme: '첫사랑, 설렘, 청춘', lyricsStyle: '밝고 순수한 표현' },
  { names: ['소유', 'soyou'], genre: 'K-R&B Pop', mood: 'warm', energy: 'medium', bpm: 88, key: 'Eb', instruments: 'piano, soft bass, gentle drums, strings, synth pad, acoustic guitar', vocalStyle: 'warm emotional female vocal with R&B sensibility and clear tone', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'warm Korean R&B pop with clear emotional female vocal and gentle arrangement', moodTags: 'warm, emotional, clear, gentle, romantic, smooth, intimate, tender, sincere, heartfelt', lyricsTheme: '사랑, 이별, 감성적 이야기', lyricsStyle: '감성적이고 따뜻한 표현' },

  // ════════════════════════════════════════
  // ── K-트로트 ──
  // ════════════════════════════════════════
  { names: ['임영웅'], genre: 'Modern Trot / Ballad', mood: 'emotional', energy: 'medium', bpm: 80, key: 'Cm', instruments: 'piano, strings, acoustic guitar, soft drums, bass, orchestral arrangement', vocalStyle: 'warm powerful male vocal with trot vibrato and ballad emotional delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-final_chorus-outro', ref: 'modern Korean trot-ballad crossover with warm powerful vocal and orchestral arrangement', moodTags: 'emotional, warm, powerful, comforting, dramatic, nostalgic, heartfelt, sincere, moving, anthemic', lyricsTheme: '사랑, 효도, 인생의 위로', lyricsStyle: '진솔하고 따뜻한 감정 표현' },
  { names: ['송가인'], genre: 'Modern Trot', mood: 'cheerful', energy: 'high', bpm: 118, key: 'G', instruments: 'synth brass, electric guitar, bass, drums, accordion, traditional percussion', vocalStyle: 'powerful female trot vocal with ornamental vibrato and dynamic range', vocalGender: 'f', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'modern Korean trot with powerful female vocal, brass arrangements and rhythmic bounce', moodTags: 'cheerful, powerful, festive, bright, dynamic, traditional, vibrant, playful, energetic, retro', lyricsTheme: '사랑, 인생, 밝은 에너지', lyricsStyle: '밝고 활기찬 트로트 감성' },
  { names: ['영탁'], genre: 'Modern Trot / Pop', mood: 'warm', energy: 'medium', bpm: 95, key: 'Bb', instruments: 'guitar, piano, bass, drums, brass, strings', vocalStyle: 'warm male trot vocal with modern pop sensibility and emotional delivery', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'modern Korean trot-pop crossover with warm vocal and contemporary arrangement', moodTags: 'warm, modern, emotional, catchy, sincere, bright, trot, pop, charming, heartfelt', lyricsTheme: '사랑, 인생, 위로', lyricsStyle: '따뜻하고 현대적인 트로트 감성' },

  // ════════════════════════════════════════
  // ── J-Pop / J-Rock ──
  // ════════════════════════════════════════
  { names: ['yoasobi', 'ヨアソビ'], genre: 'J-Pop / Electronic Pop', mood: 'energetic', energy: 'high', bpm: 130, key: 'Am', instruments: 'synth, piano, electronic drums, bass, strings, vocal processing', vocalStyle: 'bright clear female vocal with fast delivery and distinctive J-pop phrasing', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'modern J-pop with electronic production, bright female vocal and anime-influenced aesthetic', moodTags: 'energetic, bright, electronic, catchy, dynamic, modern, anime, youthful, driving, vibrant', lyricsTheme: '小説原作の物語、夜と冒険', lyricsStyle: '소설 기반 스토리텔링' },
  { names: ['ado', 'アド'], genre: 'J-Pop / Vocal Rock', mood: 'intense', energy: 'very high', bpm: 140, key: 'Cm', instruments: 'heavy electric guitar, bass, powerful drums, synth, distortion, orchestral hits', vocalStyle: 'explosive female vocal with extreme range, screaming to whisper dynamics', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-breakdown-final_chorus-outro', ref: 'intense J-pop vocal rock with explosive female vocal power and dramatic arrangement', moodTags: 'intense, explosive, powerful, dramatic, fierce, dynamic, raw, theatrical, emotional, commanding', lyricsTheme: '감정의 폭발, 내면의 갈등', lyricsStyle: '강렬하고 드라마틱한 표현' },
  { names: ['kenshi yonezu', '米津玄師', '요네즈 켄시'], genre: 'J-Pop / Art Pop', mood: 'emotional', energy: 'medium', bpm: 105, key: 'Am', instruments: 'acoustic guitar, electric guitar, piano, bass, drums, strings, electronic elements', vocalStyle: 'distinctive male vocal with artistic delivery and emotional depth', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'artistic J-pop with genre-blending production, distinctive vocal and literary storytelling', moodTags: 'emotional, artistic, deep, atmospheric, distinctive, poetic, dynamic, innovative, beautiful, complex', lyricsTheme: '인생, 사랑, 존재의 의미', lyricsStyle: '문학적이고 예술적인 가사' },
  { names: ['official hige dandism', '髭男', 'higedan'], genre: 'J-Pop / Piano Pop Rock', mood: 'emotional', energy: 'high', bpm: 118, key: 'C', instruments: 'piano, electric guitar, bass, drums, strings, synth, vocal harmonies', vocalStyle: 'high-pitched male vocal with impressive falsetto and emotional rock delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'piano-driven J-pop rock with powerful high-pitched vocal and dynamic arrangement', moodTags: 'emotional, dynamic, powerful, piano-driven, soaring, passionate, bright, anthemic, dramatic, catchy', lyricsTheme: '사랑, 이별, 감정의 깊이', lyricsStyle: '감성적이고 드라마틱한 가사' },
  { names: ['one ok rock', 'ワンオク'], genre: 'J-Rock / Alternative', mood: 'passionate', energy: 'very high', bpm: 145, key: 'Em', instruments: 'heavy guitar, bass, powerful drums, synth, orchestral elements', vocalStyle: 'powerful male vocal with rock intensity and bilingual delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-guitar_solo-final_chorus-outro', ref: 'powerful Japanese alternative rock with Western influence, intense guitar and powerful vocal', moodTags: 'passionate, powerful, intense, rock, driving, anthemic, fierce, emotional, explosive, epic', lyricsTheme: '투쟁, 사랑, 희망', lyricsStyle: '강렬하고 진솔한 영어/일본어 혼합' },
  { names: ['lisa', 'リサ', 'lisa (jpop)'], genre: 'J-Rock / Anime Rock', mood: 'passionate', energy: 'very high', bpm: 138, key: 'Dm', instruments: 'distorted guitar, bass, fast drums, synth, strings, brass', vocalStyle: 'powerful female vocal with rock intensity and anime-anthem delivery', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-final_chorus-outro', ref: 'intense J-rock anime theme with powerful female vocal and epic arrangement', moodTags: 'passionate, intense, epic, powerful, anime, driving, dramatic, fierce, anthemic, soaring', lyricsTheme: '전투, 희망, 운명에 대한 도전', lyricsStyle: '열정적이고 서사적인 표현' },

  // ════════════════════════════════════════
  // ── 해외 아티스트 (Western) ──
  // ════════════════════════════════════════
  { names: ['ed sheeran', '에드 시런'], genre: 'Acoustic Pop / Folk Pop', mood: 'warm', energy: 'medium', bpm: 96, key: 'G', instruments: 'acoustic guitar fingerpicking, loop pedal layers, light percussion, bass, strings', vocalStyle: 'warm raspy male vocal with intimate delivery and melodic storytelling', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'acoustic folk-pop with loop-based layered production and warm intimate vocal storytelling', moodTags: 'warm, intimate, acoustic, heartfelt, romantic, gentle, sincere, organic, storytelling, breezy', lyricsTheme: 'love, heartbreak, personal stories', lyricsStyle: 'narrative storytelling with poetic imagery' },
  { names: ['taylor swift', '테일러 스위프트'], genre: 'Pop / Singer-Songwriter', mood: 'emotional', energy: 'medium', bpm: 100, key: 'C', instruments: 'acoustic guitar, synth, drums, bass, piano, strings, vocal harmonies', vocalStyle: 'clear bright female vocal with narrative delivery and emotional dynamics', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'modern pop with singer-songwriter sensibility, narrative lyrics and polished production', moodTags: 'emotional, narrative, bright, empowering, nostalgic, romantic, dramatic, anthemic, personal, catchy', lyricsTheme: 'love, heartbreak, growing up, personal reflection', lyricsStyle: 'detailed narrative storytelling' },
  { names: ['the weeknd', '위켄드'], genre: 'Dark R&B / Synth Pop', mood: 'dark', energy: 'medium', bpm: 108, key: 'Fm', instruments: 'retro synth, 808 bass, electronic drums, ambient pad, vintage keys, strings', vocalStyle: 'airy falsetto male vocal with Michael Jackson influence and dark sensuality', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'dark cinematic R&B with 80s synth-pop influence, atmospheric production and falsetto vocal', moodTags: 'dark, atmospheric, cinematic, retro, sensual, moody, hypnotic, nocturnal, brooding, slick', lyricsTheme: 'dark love, nightlife, obsession, loneliness', lyricsStyle: 'dark atmospheric imagery' },
  { names: ['billie eilish', '빌리 아일리시'], genre: 'Dark Pop / Alt Pop', mood: 'dark', energy: 'low', bpm: 80, key: 'Dm', instruments: 'sub bass, minimal beats, ambient texture, whisper vocal layers, glitch elements', vocalStyle: 'whispery intimate female vocal with ASMR-like delivery and subtle power', vocalGender: 'f', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'minimalist dark pop with sub-bass heavy production, whisper vocals and bedroom-studio aesthetic', moodTags: 'dark, intimate, minimalist, haunting, whispery, moody, atmospheric, edgy, introspective, alternative', lyricsTheme: 'mental health, dark thoughts, authenticity', lyricsStyle: 'raw honest expression' },
  { names: ['adele', '아델'], genre: 'Pop Soul Ballad', mood: 'emotional', energy: 'medium', bpm: 68, key: 'Ab', instruments: 'grand piano, orchestral strings, deep bass, dramatic drums, choir', vocalStyle: 'powerful alto female vocal with extraordinary range and raw emotional delivery', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'powerful pop-soul ballad with grand piano, orchestral arrangement and devastating vocal performance', moodTags: 'emotional, powerful, dramatic, soulful, heartbreaking, raw, soaring, passionate, cinematic, devastating', lyricsTheme: 'heartbreak, loss, regret, resilience', lyricsStyle: 'deeply personal emotional storytelling' },
  { names: ['bruno mars', '브루노 마스'], genre: 'Pop Funk / Retro Pop', mood: 'groovy', energy: 'high', bpm: 115, key: 'Bb', instruments: 'funky guitar, bass slap, brass section, drums, synth, handclaps, keys', vocalStyle: 'versatile male vocal with soulful power and retro charm', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus-outro', ref: 'retro-inspired pop-funk with tight grooves, brass hooks and charismatic vocal delivery', moodTags: 'groovy, funky, retro, energetic, smooth, charming, danceable, bright, fun, slick', lyricsTheme: 'love, romance, celebration', lyricsStyle: 'catchy and charming expression' },
  { names: ['ariana grande', '아리아나 그란데'], genre: 'Pop R&B / Vocal Pop', mood: 'empowering', energy: 'high', bpm: 108, key: 'Cm', instruments: 'trap drums, synth bass, piano, strings, vocal layers, 808 hi-hats', vocalStyle: 'powerful soprano female vocal with whistle register and R&B melisma', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-final_chorus-outro', ref: 'modern vocal pop-R&B with trap-influenced beats and powerful soprano vocal showcase', moodTags: 'empowering, powerful, slick, modern, fierce, romantic, airy, danceable, polished, sultry', lyricsTheme: 'empowerment, love, independence', lyricsStyle: 'confident and catchy expression' },
  { names: ['maroon 5', '마룬 5'], genre: 'Pop Rock / Funk Pop', mood: 'groovy', energy: 'high', bpm: 115, key: 'Bb', instruments: 'funky guitar, bass, drums, synth, falsetto vocal hooks, whistle melody', vocalStyle: 'distinctive falsetto male vocal with pop-rock grit and melodic hooks', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus-outro', ref: 'catchy pop-rock with funk guitar riffs, falsetto hooks and radio-friendly production', moodTags: 'groovy, catchy, energetic, fun, bright, danceable, polished, upbeat, radio-friendly, smooth', lyricsTheme: 'love, relationships, desire', lyricsStyle: 'catchy and playful pop lyrics' },
  { names: ['drake', '드레이크'], genre: 'Hip-Hop / R&B Rap', mood: 'moody', energy: 'medium', bpm: 82, key: 'Am', instruments: 'atmospheric pad, 808 bass, trap hi-hats, ambient synth, piano, vocal samples', vocalStyle: 'male vocal with rap-singing hybrid delivery, emotional undertone', vocalGender: 'm', structure: 'intro-verse-hook-verse-hook-bridge-hook-outro', ref: 'moody atmospheric hip-hop-R&B with emotional rap-singing and atmospheric production', moodTags: 'moody, atmospheric, emotional, introspective, dark, smooth, nocturnal, personal, melancholic, urban', lyricsTheme: 'love, success, loneliness, personal struggles', lyricsStyle: 'introspective emotional rap' },
  { names: ['dua lipa', '두아 리파'], genre: 'Disco Pop / Dance Pop', mood: 'groovy', energy: 'high', bpm: 116, key: 'Fm', instruments: 'disco bass, synth, funky guitar, dance beat, strings, handclaps, retro synth', vocalStyle: 'sultry confident female vocal with disco-pop delivery', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'modern disco-pop with retro funky production, danceable grooves and sultry vocal', moodTags: 'groovy, danceable, retro, disco, fun, confident, sexy, bright, catchy, energetic', lyricsTheme: 'empowerment, love, dancing', lyricsStyle: 'confident and catchy' },
  { names: ['post malone', '포스트 말론'], genre: 'Pop Rap / Alternative Hip-Hop', mood: 'melancholic', energy: 'medium', bpm: 85, key: 'Gm', instruments: 'acoustic guitar, trap drums, 808 bass, piano, ambient synth, vocal processing', vocalStyle: 'melodic male vocal with Auto-Tune, raspy singing-rap hybrid', vocalGender: 'm', structure: 'intro-verse-hook-verse-hook-bridge-hook-outro', ref: 'genre-blending pop-rap with acoustic elements, melodic Auto-Tune vocal and melancholic vibe', moodTags: 'melancholic, melodic, atmospheric, raw, alternative, emotional, laid-back, hazy, introspective, versatile', lyricsTheme: 'heartbreak, fame, loneliness', lyricsStyle: 'melodic and emotionally raw' },
  { names: ['coldplay', '콜드플레이'], genre: 'Alternative Rock / Anthemic Pop', mood: 'uplifting', energy: 'high', bpm: 120, key: 'Eb', instruments: 'atmospheric guitar, piano, bass, drums, synth, strings, ambient layers', vocalStyle: 'emotional male falsetto with anthemic delivery and vulnerable undertone', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-climax_chorus-outro', ref: 'anthemic alternative rock-pop with atmospheric guitars, piano and emotional falsetto vocal', moodTags: 'uplifting, anthemic, atmospheric, emotional, hopeful, ethereal, epic, dreamy, inspiring, expansive', lyricsTheme: 'hope, love, the universe, human connection', lyricsStyle: 'poetic and uplifting imagery' },
  { names: ['imagine dragons', '이매진 드래곤즈'], genre: 'Alternative Rock / Arena Rock', mood: 'epic', energy: 'very high', bpm: 130, key: 'Am', instruments: 'heavy drums, bass, synth, guitar, strings, stomping percussion, choir', vocalStyle: 'powerful gravelly male vocal with anthemic stadium delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'arena alternative rock with heavy percussion, anthemic chorus and powerful gravelly vocal', moodTags: 'epic, powerful, anthemic, driving, intense, stadium, dramatic, bold, explosive, inspiring', lyricsTheme: 'struggle, resilience, overcoming obstacles', lyricsStyle: 'anthemic and motivational' },
  { names: ['queen', '퀸'], genre: 'Rock / Stadium Rock', mood: 'epic', energy: 'very high', bpm: 120, key: 'Bb', instruments: 'electric guitar, bass, drums, piano, vocal harmonies, choir, Brian May guitar layers', vocalStyle: 'legendary powerful male vocal with operatic range and theatrical delivery', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-guitar_solo-final_chorus-outro', ref: 'legendary stadium rock with operatic vocals, layered guitar harmonies and theatrical arrangement', moodTags: 'epic, legendary, theatrical, powerful, operatic, anthemic, dramatic, majestic, iconic, triumphant', lyricsTheme: 'freedom, love, life, rebellion', lyricsStyle: 'theatrical and poetic storytelling' },
  { names: ['eminem', '에미넴'], genre: 'Hip-Hop / Rap', mood: 'intense', energy: 'very high', bpm: 145, key: 'Dm', instruments: 'piano, heavy drums, bass, synth, orchestral hits, guitar', vocalStyle: 'rapid-fire male rap with technical precision and emotional intensity', vocalGender: 'm', structure: 'intro-verse-hook-verse-hook-verse-hook-outro', ref: 'intense technical hip-hop with fast complex rap, emotional storytelling and dark production', moodTags: 'intense, technical, emotional, aggressive, raw, powerful, dark, personal, fierce, complex', lyricsTheme: 'personal struggles, resilience, social commentary', lyricsStyle: 'complex wordplay and storytelling' },
  { names: ['kendrick lamar', '켄드릭 라마'], genre: 'Conscious Hip-Hop / Jazz Rap', mood: 'thoughtful', energy: 'high', bpm: 95, key: 'Fm', instruments: 'jazz piano, bass, drums, saxophone, synth, 808, live percussion', vocalStyle: 'versatile male rap with dynamic flow changes and jazz-influenced delivery', vocalGender: 'm', structure: 'intro-verse-hook-verse-hook-verse-hook-outro', ref: 'conscious hip-hop with jazz elements, complex storytelling and innovative production', moodTags: 'thoughtful, complex, conscious, jazzy, innovative, powerful, poetic, dynamic, deep, artistic', lyricsTheme: 'social justice, identity, spirituality', lyricsStyle: 'complex literary rap' },
  { names: ['beyonce', '비욘세'], genre: 'Pop R&B / Power Pop', mood: 'empowering', energy: 'high', bpm: 108, key: 'Bbm', instruments: 'powerful drums, bass, synth, brass, strings, vocal harmonies, handclaps', vocalStyle: 'powerful diva female vocal with extraordinary range and fierce delivery', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-dance_break-final_chorus-outro', ref: 'powerful pop-R&B with fierce vocal delivery, dynamic arrangement and empowering energy', moodTags: 'empowering, powerful, fierce, confident, dynamic, soulful, bold, iconic, anthemic, majestic', lyricsTheme: 'empowerment, love, independence, strength', lyricsStyle: 'powerful and empowering expression' },
  { names: ['lady gaga', '레이디 가가'], genre: 'Pop / Dance Pop', mood: 'theatrical', energy: 'very high', bpm: 120, key: 'Am', instruments: 'synth, heavy bass, electronic drums, piano, strings, vocal processing', vocalStyle: 'powerful theatrical female vocal with operatic training and pop versatility', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'theatrical dance pop with bold production, powerful vocals and avant-garde artistic vision', moodTags: 'theatrical, bold, powerful, artistic, dramatic, danceable, fierce, avant-garde, iconic, experimental', lyricsTheme: 'fame, love, self-expression, identity', lyricsStyle: 'theatrical and artistic expression' },
  { names: ['justin bieber', '저스틴 비버'], genre: 'Pop / R&B Pop', mood: 'smooth', energy: 'medium', bpm: 100, key: 'Eb', instruments: 'synth, bass, electronic drums, guitar, piano, vocal layers, trap elements', vocalStyle: 'smooth young male vocal with R&B influence and falsetto hooks', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'modern pop-R&B with smooth vocal delivery, polished production and catchy hooks', moodTags: 'smooth, catchy, modern, romantic, polished, youthful, laid-back, groovy, intimate, bright', lyricsTheme: 'love, relationships, personal growth', lyricsStyle: 'romantic and personal' },
  { names: ['olivia rodrigo', '올리비아 로드리고'], genre: 'Pop Rock / Alt Pop', mood: 'emotional', energy: 'high', bpm: 118, key: 'Am', instruments: 'distorted guitar, bass, drums, piano, strings, aggressive synth', vocalStyle: 'raw emotional female vocal with pop-punk energy and vulnerable delivery', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'emotional pop-rock with pop-punk revival influence, raw vocal and teenage angst', moodTags: 'emotional, raw, angsty, powerful, vulnerable, dramatic, catchy, youthful, fierce, bittersweet', lyricsTheme: 'heartbreak, jealousy, teenage emotions', lyricsStyle: 'raw and brutally honest' },
  { names: ['harry styles', '해리 스타일스'], genre: 'Soft Rock / Indie Pop', mood: 'warm', energy: 'medium', bpm: 105, key: 'D', instruments: 'acoustic guitar, electric guitar, bass, drums, piano, strings, retro synth', vocalStyle: 'warm rock male vocal with classic influence and vulnerable charm', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'retro-tinged soft rock with 70s influence, warm vocal and breezy indie-pop production', moodTags: 'warm, retro, breezy, charming, romantic, vintage, indie, bright, dreamy, feel-good', lyricsTheme: 'love, freedom, self-discovery', lyricsStyle: 'poetic and charming' },
  { names: ['sam smith', '샘 스미스'], genre: 'Pop Soul / Vocal Pop', mood: 'emotional', energy: 'medium', bpm: 78, key: 'Fm', instruments: 'piano, strings, bass, soft drums, choir, ambient pad', vocalStyle: 'emotional counter-tenor male vocal with soulful delivery and vulnerability', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-final_chorus-outro', ref: 'emotional pop-soul with powerful counter-tenor vocal and minimalist orchestral arrangement', moodTags: 'emotional, soulful, vulnerable, powerful, intimate, dramatic, moving, heartfelt, elegant, raw', lyricsTheme: 'love, loneliness, heartbreak', lyricsStyle: 'emotionally vulnerable and honest' },
  { names: ['sza', 'SZA'], genre: 'Alternative R&B / Neo Soul', mood: 'moody', energy: 'medium', bpm: 90, key: 'Bbm', instruments: 'warm bass, lo-fi drums, ambient synth, guitar, vocal harmonies, soft percussion', vocalStyle: 'airy intimate female vocal with R&B runs and vulnerable delivery', vocalGender: 'f', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'alternative R&B with atmospheric production, intimate airy vocal and lo-fi warmth', moodTags: 'moody, intimate, atmospheric, vulnerable, warm, dreamy, raw, sensual, emotional, alternative', lyricsTheme: 'love, insecurity, self-reflection', lyricsStyle: 'raw and introspective' },
  { names: ['frank ocean', '프랭크 오션'], genre: 'Alternative R&B / Art Pop', mood: 'introspective', energy: 'low', bpm: 78, key: 'Db', instruments: 'minimal piano, ambient synth, subtle bass, soft drums, vocal layers, atmospheric texture', vocalStyle: 'airy introspective male vocal with falsetto and subtle emotional shifts', vocalGender: 'm', structure: 'intro-verse-chorus-verse-chorus-bridge-outro', ref: 'minimalist alternative R&B with atmospheric production, introspective vocal and artistic sensibility', moodTags: 'introspective, atmospheric, minimalist, artistic, ethereal, intimate, poetic, experimental, dreamy, profound', lyricsTheme: 'love, nostalgia, identity, existential reflection', lyricsStyle: 'poetic and deeply personal' },
  { names: ['weeknd', 'abel tesfaye'], genre: 'Dark R&B / Synth Pop', mood: 'dark', energy: 'medium', bpm: 108, key: 'Fm', instruments: 'retro synth, 808 bass, electronic drums, ambient pad, vintage keys, strings', vocalStyle: 'airy falsetto male vocal with Michael Jackson influence and dark sensuality', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'dark cinematic R&B with 80s synth-pop influence, atmospheric production and falsetto vocal', moodTags: 'dark, atmospheric, cinematic, retro, sensual, moody, hypnotic, nocturnal, brooding, slick', lyricsTheme: 'dark love, nightlife, obsession, loneliness', lyricsStyle: 'dark atmospheric imagery' },
  { names: ['lana del rey', '라나 델 레이'], genre: 'Dream Pop / Baroque Pop', mood: 'melancholic', energy: 'low', bpm: 75, key: 'Dm', instruments: 'reverb guitar, strings, piano, deep bass, vintage drum machine, harp, ambient pad', vocalStyle: 'breathy sultry female vocal with vintage Hollywood glamour and melancholic delivery', vocalGender: 'f', structure: 'intro-verse-chorus-verse-chorus-bridge-chorus-outro', ref: 'cinematic dream pop with vintage aesthetic, lush orchestration and breathy nostalgic vocal', moodTags: 'melancholic, cinematic, dreamy, nostalgic, vintage, sultry, atmospheric, romantic, dark, ethereal', lyricsTheme: 'tragic romance, nostalgia, American dream, beauty and sadness', lyricsStyle: 'cinematic and poetic imagery' },
  { names: ['travis scott', '트래비스 스캇'], genre: 'Psychedelic Trap / Hip-Hop', mood: 'dark', energy: 'high', bpm: 145, key: 'Cm', instruments: 'heavy 808, dark synth, auto-tune vocal layers, distorted bass, ambient pad, sirens', vocalStyle: 'auto-tuned male vocal with psychedelic ad-libs and atmospheric delivery', vocalGender: 'm', structure: 'intro-verse-hook-verse-hook-bridge-hook-outro', ref: 'psychedelic trap with heavy 808s, atmospheric auto-tune vocal and dark ambient production', moodTags: 'dark, psychedelic, atmospheric, heavy, hypnotic, distorted, trippy, intense, spacey, bass-heavy', lyricsTheme: 'nightlife, psychedelic experience, fame', lyricsStyle: 'atmospheric and abstract' },
  { names: ['bts', 'jimin', '지민'], genre: 'K-Pop / Contemporary R&B', mood: 'emotional', energy: 'medium', bpm: 90, key: 'Fm', instruments: 'synth, piano, bass, soft drums, strings, ambient pad, vocal layers', vocalStyle: 'ethereal high-pitched male vocal with delicate falsetto and emotional intensity', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-chorus-outro', ref: 'emotional K-pop with contemporary R&B influence and ethereal high-pitched vocal', moodTags: 'emotional, ethereal, delicate, atmospheric, passionate, intimate, dreamy, powerful, modern, beautiful', lyricsTheme: '사랑, 외로움, 내면의 감정', lyricsStyle: '감성적이고 섬세한 표현' },
  { names: ['charlie puth', '찰리 푸스'], genre: 'Pop / Synth Pop', mood: 'bright', energy: 'medium', bpm: 105, key: 'Bb', instruments: 'synth, bass, electronic drums, piano, vocal harmonies, guitar, retro keys', vocalStyle: 'clear male vocal with falsetto hooks and precise musical delivery', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus-outro', ref: 'polished pop with musical precision, catchy synth-pop production and clear vocal delivery', moodTags: 'bright, catchy, polished, modern, musical, smooth, fun, romantic, pop, slick', lyricsTheme: 'love, attraction, relationships', lyricsStyle: 'catchy and relatable' },
  { names: ['rihanna', '리한나'], genre: 'Pop R&B / Dance Pop', mood: 'fierce', energy: 'high', bpm: 115, key: 'Gm', instruments: 'heavy bass, electronic drums, synth, vocal processing, dancehall elements, piano', vocalStyle: 'distinctive Caribbean-influenced female vocal with fierce attitude and pop sensibility', vocalGender: 'f', structure: 'intro-verse-prechorus-chorus-verse-chorus-bridge-final_chorus-outro', ref: 'fierce pop-R&B with Caribbean influence, heavy production and iconic vocal delivery', moodTags: 'fierce, confident, danceable, iconic, bold, dark, sultry, powerful, bass-heavy, catchy', lyricsTheme: 'empowerment, love, confidence', lyricsStyle: 'bold and confident' },
  { names: ['michael jackson', '마이클 잭슨'], genre: 'Pop / Funk Pop', mood: 'groovy', energy: 'very high', bpm: 115, key: 'Am', instruments: 'funky bass, synth, brass, drums, guitar, strings, percussion, vocal beatbox', vocalStyle: 'legendary male vocal with hiccup technique, falsetto and rhythmic precision', vocalGender: 'm', structure: 'intro-verse-prechorus-chorus-verse-prechorus-chorus-bridge-dance_break-final_chorus-outro', ref: 'legendary pop with funk grooves, iconic vocal style and groundbreaking production', moodTags: 'groovy, iconic, legendary, funky, energetic, danceable, powerful, dramatic, dynamic, timeless', lyricsTheme: 'love, social issues, self-expression', lyricsStyle: 'catchy and iconic' },
];
